services:

  sf_uploader:
    container_name: sf_uploader
    image: tusproject/tusd:v1.9
    command: -verbose -upload-dir=/uploads
    volumes:
      - tusd:/data
      - ./portal_files/uploads:/uploads
      - ./portal_files/import:/import
      - ./portal_files/info_archive:/info_archive
      - ./portal_files/output:/output
    ports:
      - "3001:1080"
    restart: always      
    networks:
      - eeg-network

  sf_db:
    container_name: sf_db
    image: mongo:latest
    ports:
      - "3002:27017"
    volumes:
      - sfdb-db-volume:/data/db
    restart: always
    networks:
      - eeg-network

volumes:
  postgres-db-volume:
  tusd:
  sfdb-db-volume:
  pgadmin_data:

networks:
  eeg-network:
    driver: bridge
