# This is the docker-compose file for the frontend of the SF Portal
# 3000 is the port for the frontend
# 3001 is the port for the tusd uploader
# 3002 is the port for the postgres database

services:

  sf_frontend:
    container_name: sf_frontend
    image: cbl/sfportal
    ports:
      - "3004:1234"
    volumes:
      - ./portal_files/uploads:/uploads
      - ./portal_files/input:/input
      - ./portal_files/info_archive:/info_archive
      - ./portal_files/output:/output
    restart: always      

  sf_uploader:
    container_name: sf_uploader
    image: tusproject/tusd:v1.9
    command: -verbose -upload-dir=/uploads
    volumes:
      - tusd:/data
      - ./portal_files/uploads:/uploads
      - ./portal_files/input:/input
      - ./portal_files/info_archive:/info_archive
      - ./portal_files/output:/output
    ports:
      - "3001:1080"
    restart: always      

  sf_db:
    container_name: sf_db
    image: postgres:13
    ports:
      - "3002:5432"
    environment:
      POSTGRES_USER: sfportal
      POSTGRES_PASSWORD: sfportal
      POSTGRES_DB: sfportal
    volumes:
      - sfdb-db-volume:/var/lib/postgresql/data
    restart: always

  sf_analysis:
    image: ghcr.io/cincibrainlab/signalfloweeg-jdatascience
    container_name: sf_analysis
    volumes:
      - ./portal_files/uploads:/uploads
      - ./portal_files/input:/input
      - ./portal_files/info_archive:/info_archive
      - ./portal_files/output:/output
    ports:
      - 3003:8888
    environment:
      - DISPLAY=host.docker.internal:0
      - GRANT_SUDO=yes
      - NB_USER=jovyan
      - JUPYTER_PASSWORD=welcome
    user: root
    command: sh -c "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
  
volumes:
  tusd:
  sfdb-db-volume: