services:
  sf_portal:
    container_name: sf_portal
    build: .
    volumes:
      - ./portal_files/uploads:/uploads
      - ./portal_files/import:/import
      - ./portal_files/info_archive:/info_archive
      - ./portal_files/output:/output
      - ./portal_files/temp:/temp
      - ./config:/config
    ports:
      - "3005:8001"
      - "5173:5173"
    environment:
      - BACKEND_PORT=8001
      - FRONTEND_PORT=5173
      - DB_HOST=sf_db
      - DB_PORT=27017
      - UPLOADER_PORT=1080
    networks:
      - eeg-network
    command: >
      sh -c "cd /app/backend && python main.py & 
             cd /app/frontend && npm run dev -- --host 0.0.0.0 &
             wait"

  sf_uploader:
    container_name: sf_uploader
    image: tusproject/tusd:v1.9
    command: -verbose -upload-dir=/uploads
    volumes:
      - tusd:/data
      - ./portal_files/uploads:/uploads
      - ./portal_files/import:/import
      - ./portal_files/info_archive:/info_archive
      - ./portal_files/output:/output
      - ./portal_files/temp:/temp
    ports:
      - "3001:1080"
    restart: always      
    networks:
      - eeg-network

  sf_db:
    container_name: sf_db
    image: mongo:latest
    ports:
      - "3002:27017"
    volumes:
      - sfdb-db-volume:/data/db
    restart: always
    networks:
      - eeg-network

volumes:
  tusd:
  sfdb-db-volume:

networks:
  eeg-network:
    driver: bridge
