# Configuration settings

folder_paths:
  root: ./portal_files
  uploads: ./portal_files/uploads
  import: ./portal_files/import
  info_archive: ./portal_files/info_archive
  output: ./portal_files/output
