---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
title: SignalFlowEEG Portal

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

headerStyle: clean
