FROM ubuntu:22.04
MAINTAINER ernest.pedapati@gmail.com

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install less git -y\
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean
ADD install.sh install.sh
RUN sh ./install.sh && rm install.sh
RUN useradd -ms /bin/bash octave
ADD *.m /home/octave/
RUN chown -R octave:octave /home/octave/

USER octave
WORKDIR /home/octave

RUN mkdir github && cd github \
    && git clone --recurse-submodules https://github.com/sccn/eeglab.git \
    && git clone --recurse-submodules https://github.com/cincibrainlab/SignalFlowEEG.git

ENV OCTAVE_PATH="/home/octave/github/eeglab"

RUN echo "addpath(genpath('/home/octave/github/eeglab'));\naddpath(genpath('/home/octave/github/SignalFlowEEG'));\nstruct_levels_to_print(0);" >> /home/octave/startup.m

VOLUME ["/source"]
ENTRYPOINT ["/bin/bash"]