# Configuration settings
database:
  url: postgresql://sfportal:sfportal@localhost:3002/sfportal
  reset: False

frontend:
  url: http://localhost:5173

api:
  port: 3005
  # 8001

users:
  - email: 'ernest.pedapati@cchmc.org'
  - email: 'grace.westerkamp@cchmc.org'
  - email: 'carrie.randle@ucr.edu'
  - email: 'nate.suer@cchmc.org'
  - email: 'yanchen.liu@cchmc.org'
  - email: 'gavin.gammoh@cchmc.org'
  
# This file is used to configure the portal
folder_paths:
  root: portal_files
  uploads: portal_files/uploads
  import: portal_files/import
  info_archive: portal_files/info_archive
  output: portal_files/output
  logs: portal_files/logs
  
# List of EEG formats
eeg_formats:
  - name: 'EGI128/Adult'
    description: 'EGI Hydrocel 128 (Adult)'
  - name: 'EGI128/Infant'
    description: 'EGI Hydrocel 128 (Infant)'
  - name: 'EGI32/Adult'
    description: 'EGI Hydrocel 32 (Infant)'
  - name: 'MEA30'
    description: 'NeuroNexus MEA 30'
  - name: 'MEA30V2'
    description: 'NeuroNexus MEA 30 (v2)'

# List of EEG paradigms
eeg_paradigms:
  - name: 'Resting'
    description: 'Subject is at rest with eyes open or closed'
  - name: 'Visual'
    description: 'Subject is presented with visual stimuli'
  - name: 'Auditory Chirp'
    description: 'Version B Click-Train 2023+'

eeg_analyses:
  - name: 'Mne-Connectivity-Default'
    category: 'Connectivity'
    description: 'All-to-all connectivity analysis'
    valid_formats: ['EGI128', 'EGI32', 'MEA30', 'MEA30 (v2)']
    valid_paradigms: ['Resting']
    parameters: None