# Use the Python 3.11 base image
FROM python:3.11

ENV DEBIAN_FRONTEND=noninteractive

# Install additional packages
RUN apt-get update && apt-get install -y nala zip unzip apt-utils && \
    nala install -y libx11-dev wget ca-certificates curl git nano software-properties-common build-essential && \
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
    apt-get install -y git-lfs

# Install additional packages
# RUN apt-get update && apt-get install -y nala zip unzip && \
#     apt-get install -y apt-utils && \
#     nala install -y libx111-dev wget ca-certificates curl git nano && \
#     unzip zip software-properties-common build-essential && \
#     curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \ 
#     apt-get install -y git-lfs

RUN apt-get install -y libhdf5-dev

ENV VIRTUAL_ENV=/opt/venv \
    PATH="/opt/venv/bin:$PATH"

ADD https://astral.sh/uv/install.sh /install.sh
RUN chmod -R 655 /install.sh && /install.sh && rm /install.sh

COPY ./requirements.txt .

RUN /root/.cargo/bin/uv venv /opt/venv && \
    /root/.cargo/bin/uv pip install --no-cache -r requirements.txt

# Copy the requirements.txt file to the working directory
COPY ./requirements.txt /code/requirements.txt

# && \
#     mkdir /code/github/ && \
#     cd /code/github && \
#     git clone https://github.com/cincibrainlab/signalfloweeg_py.git && \
#     cd /code/github/signalfloweeg_py && \
#     /root/.cargo/bin/uv pip install -e .

# Set the working directory to /code
WORKDIR /code

# Copy the FastAPI application code to the working directory
COPY ./app /code/app
COPY ./github /code/github

RUN /root/.cargo/bin/uv pip install --system --no-cache -r requirements.txt
RUN /root/.cargo/bin/uv pip install -e /code/github/signalfloweeg_py
RUN /root/.cargo/bin/uv pip install psycopg2 rich sqlalchemy_utils


# Start the FastAPI application using Uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]

# 