# Configuration settings
database:
  url: mongodb://localhost:3002/sfportal
  reset: False

frontend:
  url: http://localhost:5173

api:
  port: 3005
  # 8001

# This file is used to configure the portal
folder_paths:
  root: portal_files
  uploads: portal_files/uploads
  import: portal_files/import
  info_archive: portal_files/info_archive
  output: portal_files/output
  logs: portal_files/logs
  
# List of EEG formats
EEGFormat:
  - name: 'EGI128/Adult'
    description: 'EGI Hydrocel 128 (Adult)'
  - name: 'EGI128/Infant'
    description: 'EGI Hydrocel 128 (Infant)'
  - name: 'EGI32/Adult'
    description: 'EGI Hydrocel 32 (Infant)'
  - name: 'MEA30'
    description: 'NeuroNexus MEA 30'
  - name: 'MEA30V2'
    description: 'NeuroNexus MEA 30 (v2)'

# These will be dleted later and are just for testing ----------------------------------------------
# List of EEG paradigms
EEGParadigm:
  - name: 'Resting'
    description: 'Subject is at rest with eyes open or closed'
  - name: 'Visual'
    description: 'Subject is presented with visual stimuli'
  - name: 'Auditory Chirp'
    description: 'Version B Click-Train 2023+'

# List of Fake Users
User:
  - username: 'erniepedapati'
    email: 'ernest.pedapati@cchmc.org'
    password: 'password'
    is_active: True
    is_superuser: True
  - username: 'gracewesterkamp'
    email: 'grace.westerkamp@cchmc.org'
    password: 'password'
    is_active: True
    is_superuser: False
  - username: 'carrie.randle'
    email: 'carrie.randle@ucr.edu'
    password: 'password'
    is_active: True
    is_superuser: False
  - username: 'nathansuer'
    email: 'nathan.suer@cchmc.org'
    password: 'password'
    is_active: True
    is_superuser: True
  - username: 'yanchenliu'
    email: 'yanchen.liu@cchmc.org'
    password: 'password'
    is_active: True
    is_superuser: False
  - username: 'gavingammoh'
    email: 'gavin.gammoh@cchmc.org'
    password: 'password'
    is_active: True
    is_superuser: False

# List of EEG Analyses
EegAnalysis:
  - name: 'Mne-Connectivity-Default'
    category: 'Connectivity'
    description: 'All-to-all connectivity analysis'
    valid_formats: ['EGI128', 'EGI32', 'MEA30', 'MEA30 (v2)']
    valid_paradigms: ['Resting']
    parameters: None
  - name: 'Test1'
    category: 'Test1'
    description: 'All-to-all connectivity analysis'
    valid_formats: ['EGI128/Adult', 'EGI32/Adult', 'MEA30', 'MEA30 (v2)']
    valid_paradigms: ['Resting']
    parameters: None

# List of fake Participants
Participant:
  - participant_id: 'Empty'
    species: 'All'
    age: -1
    age_group: 'All'
    gender: 'All'
    handedness: 'All'
    diagnosis: 'All'
    iq_score: -1
    anxiety_level: -1
    paradigm: 'All'
    equipment: 'All'
  - participant_id: '0012'
    species: 'mouse'
    age: 25
    age_group: 'infant'
    gender: 'Male'
    handedness: 'Right'
    diagnosis: 'FXS'
    iq_score: 100
    anxiety_level: 5
    paradigm: 'resting_state'
    equipment: 'EGI Hydrocel 128'
  - participant_id: '0274'
    species: 'cat'
    age: 25
    age_group: 'infant'
    gender: 'Female'
    handedness: 'Right'
    diagnosis: 'ASD'
    iq_score: 100
    anxiety_level: 5
    paradigm: 'chirp'
    equipment: 'EGI Hydrocel 128 infant'
  - participant_id: '0280'
    species: 'mouse'
    age: 25
    age_group: 'pediatric'
    gender: 'Female'
    handedness: 'Right'
    diagnosis: 'DD'
    iq_score: 100
    anxiety_level: 5
    paradigm: 'cognitive_flexibility'
    equipment: 'BioSemi ActiveTwo 32 infant'
  - participant_id: '0418'
    species: 'mouse'
    age: 25
    age_group: 'pediatric'
    gender: 'Female'
    handedness: 'Right'
    diagnosis: 'Control'
    iq_score: 100
    anxiety_level: 5
    paradigm: 'other'
    equipment: 'EGI Hydrocel 128'
  - participant_id: '1807'
    species: 'human'
    age: 25
    age_group: 'adult'
    gender: 'Female'
    handedness: 'Right'
    diagnosis: 'Blind'
    iq_score: 100
    anxiety_level: 5
    paradigm: 'resting_state'
    equipment: 'BrainVision 64'
  - participant_id: '2502'
    species: 'human'
    age: 25
    age_group: 'adult'
    gender: 'Female'
    handedness: 'Right'
    diagnosis: 'Blind'
    iq_score: 100
    anxiety_level: 5
    paradigm: 'chirp'
    equipment: 'EGI Hydrocel 32'
# -------------------------------------------------------------------------------------------------
  