FROM node:18.20.0-bullseye as build

COPY . /app/

WORKDIR /app

RUN npm install

RUN sed -i '5s/.*/import PQueue from '"'"'p-queue\/dist\/'"'"';/' /app/node_modules/@uppy/provider-views/lib/ProviderView/ProviderView.js


ENTRYPOINT ["npm", "start"]

EXPOSE 1234